export const ENTRIES_CSV_COLUMNS = [
  { key: "entry_id", header: "Entry ID" },
  { key: "entry_date", header: "Entry Date" },
  { key: "company_name", header: "Company Name" },
  { key: "guest_name", header: "Guest Name" },
  { key: "agent_name", header: "Company Agent" },
  { key: "vehicle_number", header: "Vehicle Number" },
  { key: "cab_type", header: "Cab Type" },
  { key: "slot", header: "Slot" },
  { key: "start_time", header: "Start Time" },
  { key: "end_time", header: "End Time" },
  { key: "time_taken", header: "Time Taken" },
  { key: "kms", header: "KMs" },
  { key: "hours", header: "Hours" },
  { key: "rate", header: "Rate" },
  { key: "extra_per_hour", header: "Extra Per Hour" },
  { key: "extra_per_km", header: "Extra Per KM" },
  { key: "extra_time_cost", header: "Extra Time Cost" },
  { key: "extra_kms_cost", header: "Extra KMs Cost" },
  { key: "tolls", header: "Tolls" },
  { key: "bata", header: "Bata" },
  { key: "total", header: "Total" },
  { key: "user_name", header: "SSM Agent" },
];
